[Global]
duration: 30
period: -1
multithreading: true
threads: 16
# VERBOSITY
verbose: true

##############
# REAL UE
##############
[UE]
ue_id: idReal
# Type 1 = SIM UE
# Type 0 = REAL UE
ue_type: 0
# UL Netfilter Queue index
ul_queue_n: 0
dl_queue_n: 1
n_ues: 0
# UE CONFIG
n_antennas: 1
alpha_ul: 0.8
nominal_pusch_p0: -60 
set_ul_pow: true
tx_power_ul: 23
cqi_period: 5
ri_period: 5
scaling_factor: 1
random_v: false
    
# LOG DATA
log_freq: 100
log_ue: true
log_quality: true
log_traffic: true
log_mobility: true
# TRAFFIC MODEL CONFIG
traffic_type: 0
ul_target: 200.0
dl_target: 200.0
var_perc: 0.10
pkt_size: 12000
# MOBILITY MODEL CONFIG
mobility_type: 4
pos_x: -90
pos_y: 97.9
random_init: false
speed: 100.0 #in km/h
speed_var: 0.0
max_distance: 5000
time_target: 5
time_target_var: 0
# PRIORITY
priority: 1
# METRIC COFIGURATION
delta_metric: 1.0
delay_t_metric: 0.1
beta_metric: 0.5
# SCENARIO
ue_height: 1.5
o2i: 13 #OUTDOOR 10, IN_BUILDING 11, IN_CAR 12, RANDOM 13

##############
# SIMULATED UE 
##############
[UE]
ue_id: idSimulated
# Type 1 = SIM UE
# Type 0 = REAL UE
ue_type: 1
n_ues: 3
n_antennas: 4
alpha_ul: 0.8
nominal_pusch_p0: -50 
set_ul_pow: true
tx_power_ul: 23
cqi_period: 1
ri_period: 1
scaling_factor: 1
random_v: false

# LOG DATA
log_freq: 1
log_ue: true
log_quality: true
log_traffic: true
log_mobility: true
# TRAFFIC MODEL CONFIG
traffic_type: 0
ul_target: 1000.0
dl_target: 1000.0
var_perc: 0.10
pkt_size: 12000
# MOBILITY MODEL CONFIG
mobility_type: 4#STATIC_MODEL 0, RANDOM_WALK_MODEL 1, RANDOM_WAYPOINT_MODEL 2, RANDOM_MANHATTAN_MODEL 3, LINEAR_DRIFT_MODEL 4, CLOCKWISE_MODEL 5
pos_x: -10
pos_y: 10
random_init: false
speed: 120.0 #in km/h
speed_var: 0.0
max_distance: 50000
time_target: 5
time_target_var: 0
# PRIORITY
priority: 4
# METRIC COFIGURATION
delta_metric: 1.0
delay_t_metric: 0.1
beta_metric: 0.01
# SCENARIO
ue_height: 1.5
o2i: 10 #OUTDOOR 10, IN_BUILDING 11, IN_CAR 12,RANDOM 13

##############
# SIMULATED UES 
##############
[UE]
ue_id: idSimulated2
# Type 1 = SIM UE
# Type 0 = REAL UE
ue_type: 1
n_ues: 0
n_antennas: 4
alpha_ul: 0.8
nominal_pusch_p0: -60 
set_ul_pow: true
tx_power_ul: 23
cqi_period: 5
ri_period: 5
scaling_factor: 1
random_v: false
# LOG DATA
log_freq: 100
log_ue: true
log_quality: true
log_traffic: true
log_mobility: true
# TRAFFIC MODEL CONFIG
traffic_type: 0
ul_target: 20.0
dl_target: 20.0
var_perc: 0.10
pkt_size: 12000
# MOBILITY MODEL CONFIG
mobility_type: 4#STATIC_MODEL 0, RANDOM_WALK_MODEL 1, RANDOM_WAYPOINT_MODEL 2, RANDOM_MANHATTAN_MODEL 3, LINEAR_DRIFT_MODEL 4
pos_x: -9
pos_y: 14
random_init: true
speed: 0.0 #in km/h
speed_var: 0.0
max_distance: 5000
time_target: 5
time_target_var: 0
# PRIORITY
priority: 4
# METRIC COFIGURATION
delta_metric: 1.0
delay_t_metric: 0.1
beta_metric: 0.01
# SCENARIO
ue_height: 1.5
o2i: 13 #OUTDOOR 10, IN_BUILDING 11, IN_CAR 12,RANDOM 13

#################
# SCENARIO CONFIG
#################
[Scenario]
scenario_type: 2  #URBAN_MICROCELL 0, URBAN_MACROCELL 1, RURAL_MACROCELL 2,INDOOR_HOTSPOT 3, INDOOR_FACTORY 4
#street_width: 10
#antenna_height: 1
#enb_height: 5
############
# eNB CONFIG
############
[eNBConfig]
# 64QAM - 0 / 256QAM - 1
modulation_m: 1
target_ber: 0.000000005
# Wideband - 0 / Subband - 1
cqi_mode: 0
tx_power: 43 #in dBm
eNB_gain: 8.7 #eNB antenna
UT_gain: 0 #UT antenna
power_boost: 2 #this is for RSRP calculation
frequency: 3500000000.0
bandwidth: 20000000

#######################
# PDCP/RLC Layer CONFIG
#######################
[PDCP_RLC]
# PDCP CONFIG
backhaul_d: 0.003
backhaul_d_var: 0.0
# RLC LAYER
order_pkts: true

##################
# MAC Layer CONFIG
##################
[MACLayer]
# METRIC COFIGURATION
metric_type: 5 #METRIC_FIFO 0, METRIC_BET 1, METRIC_DIST_DELAY 2, METRIC_W_DELAY 3, METRIC_MAX_TP 4, METRIC_RR 5, METRIC_PF 6
# LOG DATA
log_freq: 10
log_mac: true
# MAC LAYER
mimo_layers: 1 
ofdm_symbols: 14
numerology: 0
# PDCP UL CONFIG
max_rtx_ul: 4
# PDCP DL CONFIG
max_rtx_dl: 4
# Use MCS tables or SNR Gap Eq.
mcs_tables: false
# Time grouping (1 is grouping)
scheduling_mode: 0
# Freq grouping (0 is grouping)
scheduling_type: 1
scheduling_config: 1
# 1 : FDD - 0 : TDD
duplexing_type: 0
#If TDD
n_dl_slots: 7
n_ul_slots: 3
transition_c: 54
#If FDD
ratio_DL_UL: 0.7# BW percentage occupied by the DL 

##################
# PHY Layer CONFIG
##################
[PHYLayer]
# NOISE INTERFERENCE
interference_ues: 5 
interference_eNBs: 1
distance_interference: 3500
interfered_bandwidth_ratio: 0.1
enb_noise_figure: 2
ut_noise_figure: 9
# Modeled delays UL
air_delay_var_ul: 0.0
rtx_period_ul: 0.004
rtx_period_var_ul: 0
rtx_proc_delay_ul: 0.002
rtx_proc_delay_var_ul: 0.0
# Modeled delays DL
air_delay_var_dl: 0.0
rtx_period_dl: 0.005
rtx_period_var_dl: 0
rtx_proc_delay_dl: 0.002
rtx_proc_delay_var_dl: 0.0

