# Offline example: UMi n40 NPN study UE with walking background users.
[Global]
duration: 180
period: -1
multithreading: true
threads: 16
verbose: true

[UE]
ue_id: studyNPN
ue_type: 1
n_ues: 1
n_antennas: 1
alpha_ul: 0.8
nominal_pusch_p0: -60
set_ul_pow: true
tx_power_ul: 23
cqi_period: 5
ri_period: 5
scaling_factor: 1
random_v: true
log_freq: 100
log_ue: true
log_quality: true
log_traffic: true
log_mobility: true
traffic_type: 0
ul_target: 15.0
dl_target: 30.0
var_perc: 0.10
pkt_size: 12000
mobility_type: 4
pos_x: 150
pos_y: 0
random_init: false
speed: 4.0
speed_var: 1.0
max_distance: 500
time_target: 5
time_target_var: 0
priority: 20
delta_metric: 1.0
delay_t_metric: 0.1
beta_metric: 0.5
pkt_delay_budget: 0.300
l4s_dual_queue: false
l4s_target_ms: 15
l4s_rtt_max_ms: 100
l4s_min_th_us: 800
l4s_range_us: 400
l4s_k: 2.0
l4s_classic_guard_ms: 1.0
ue_height: 1.5
o2i: 10

[UE]
ue_id: backgroundNPN
ue_type: 1
n_ues: 10
n_antennas: 4
alpha_ul: 0.8
nominal_pusch_p0: -50
set_ul_pow: true
tx_power_ul: 23
cqi_period: 5
ri_period: 5
scaling_factor: 1
random_v: true
log_freq: 100
log_ue: true
log_quality: true
log_traffic: true
log_mobility: true
traffic_type: 0
ul_target: 2.0
dl_target: 2.0
var_perc: 0.10
pkt_size: 12000
mobility_type: 3
pos_x: 0
pos_y: 100
random_init: true
speed: 4.0
speed_var: 1.0
max_distance: 500
time_target: 5
time_target_var: 0
priority: 1
delta_metric: 1.0
delay_t_metric: 0.1
beta_metric: 0.01
pkt_delay_budget: 0.300
l4s_dual_queue: false
l4s_target_ms: 15
l4s_rtt_max_ms: 100
l4s_min_th_us: 800
l4s_range_us: 400
l4s_k: 2.0
l4s_classic_guard_ms: 1.0
ue_height: 1.5
o2i: 10

[Scenario]
scenario_type: 0

[eNBConfig]
modulation_m: 1
target_ber: 0.00005
cqi_mode: 1
tx_power: 43
eNB_gain: 8.7
UT_gain: 0
power_boost: 2
frequency: 2380000000.0
bandwidth: 20000000

[PDCP_RLC]
backhaul_d: 0.003
backhaul_d_var: 0.0
order_pkts: true

[MACLayer]
metric_type: 6
log_freq: 10
log_mac: true
mimo_layers: 1
n_ofdm_syms: 14
n_re_freq: 12
numerology: 1
max_rtx_ul: 4
max_rtx_dl: 4
mcs_tables: true
scheduling_mode: 1
scheduling_type: 0
scheduling_config: 1
duplexing_type: 0
n_dl_slots: 7
n_ul_slots: 3
transition_c: 54
ratio_DL_UL: 0.5

[PHYLayer]
interference_ues: 2
interference_eNBs: 1
distance_interference: 3500
interfered_bandwidth_ratio: 0.1
thermal_noise: -174
enb_noise_figure: 2
ut_noise_figure: 9
air_delay_var_ul: 0.0
rtx_period_ul: 0.004
rtx_period_var_ul: 0
rtx_proc_delay_ul: 0.002
rtx_proc_delay_var_ul: 0.0
air_delay_var_dl: 0.0
rtx_period_dl: 0.005
rtx_period_var_dl: 0
rtx_proc_delay_dl: 0.002
rtx_proc_delay_var_dl: 0.0
